#include "host/switch/switch_fs.hpp"

#include "common/platform/paths.hpp"

#include <cstdlib>
#include <system_error>

namespace archstreamer {

std::optional<std::filesystem::path> switch_path_from_env(std::string_view key) {
    if (const char* value = std::getenv(std::string(key).c_str()); value != nullptr && *value != '\0') {
        return std::filesystem::path{value};
    }
    return std::nullopt;
}

std::filesystem::path switch_home_dir() {
    if (const auto home = user_home_directory(); !home.empty()) {
        return home;
    }
    if (const char* home = std::getenv("HOME"); home != nullptr && *home != '\0') {
        return home;
    }
    return {};
}

void switch_copy_file_if_missing(
    const std::filesystem::path& source,
    const std::filesystem::path& destination) {
    if (!std::filesystem::is_regular_file(source)) {
        return;
    }
    if (std::filesystem::exists(destination)) {
        return;
    }
    std::filesystem::create_directories(destination.parent_path());
    std::filesystem::copy_file(source, destination, std::filesystem::copy_options::skip_existing);
}

void switch_copy_key_files(
    const std::filesystem::path& source_dir,
    const std::filesystem::path& destination_dir) {
    if (!std::filesystem::is_directory(source_dir)) {
        return;
    }
    std::filesystem::create_directories(destination_dir);
    for (const auto& name : {"prod.keys", "title.keys", "key_retail.bin", "title.keys_autogenerated"}) {
        switch_copy_file_if_missing(source_dir / name, destination_dir / name);
    }
}

bool switch_directory_has_entries(const std::filesystem::path& path) {
    std::error_code ec;
    if (!std::filesystem::is_directory(path, ec)) {
        return false;
    }
    const auto it = std::filesystem::directory_iterator(path, ec);
    return !ec && it != std::filesystem::directory_iterator{};
}

void switch_copy_directory_recursive_skip_existing(
    const std::filesystem::path& source,
    const std::filesystem::path& destination) {
    std::filesystem::create_directories(destination);
    for (const auto& entry : std::filesystem::recursive_directory_iterator(source)) {
        const auto relative = std::filesystem::relative(entry.path(), source);
        const auto target = destination / relative;
        if (entry.is_directory()) {
            std::filesystem::create_directories(target);
            continue;
        }
        if (!entry.is_regular_file() && !entry.is_symlink()) {
            continue;
        }
        std::filesystem::create_directories(target.parent_path());
        std::error_code ec;
        std::filesystem::copy(
            entry.path(),
            target,
            std::filesystem::copy_options::skip_existing |
                std::filesystem::copy_options::copy_symlinks,
            ec);
    }
}

} // namespace archstreamer
