#include "host/standalone_emulator.hpp"

#include "common/platform/paths.hpp"

#include <algorithm>
#include <cctype>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <functional>
#include <iostream>
#include <iterator>
#include <stdexcept>
#include <string>
#include <string_view>
#include <system_error>
#include <vector>

namespace archstreamer {
namespace {

std::optional<std::filesystem::path> path_from_env(std::string_view key) {
    if (const char* value = std::getenv(std::string(key).c_str()); value != nullptr && *value != '\0') {
        return std::filesystem::path{value};
    }
    return std::nullopt;
}

std::filesystem::path home_dir() {
    if (const auto home = user_home_directory(); !home.empty()) {
        return home;
    }
    if (const char* home = std::getenv("HOME"); home != nullptr && *home != '\0') {
        return home;
    }
    return {};
}

void copy_file_if_missing(const std::filesystem::path& source, const std::filesystem::path& destination) {
    if (!std::filesystem::is_regular_file(source)) {
        return;
    }
    if (std::filesystem::exists(destination)) {
        return;
    }
    std::filesystem::create_directories(destination.parent_path());
    std::filesystem::copy_file(source, destination, std::filesystem::copy_options::skip_existing);
}

void copy_key_files(const std::filesystem::path& source_dir, const std::filesystem::path& destination_dir) {
    if (!std::filesystem::is_directory(source_dir)) {
        return;
    }
    std::filesystem::create_directories(destination_dir);
    for (const auto& name : {"prod.keys", "title.keys", "key_retail.bin", "title.keys_autogenerated"}) {
        copy_file_if_missing(source_dir / name, destination_dir / name);
    }
}

// Yuzu/QSettings: unquoted commas truncate values (bindings become just "pad:0").
std::string quote_qt_ini_value(std::string_view value) {
    if (value == "[empty]") {
        return "[empty]";
    }
    const bool needs_quotes =
        value.find_first_of(",;\"\n\r") != std::string_view::npos;
    if (!needs_quotes) {
        return std::string(value);
    }
    std::string quoted;
    quoted.reserve(value.size() + 2);
    quoted.push_back('"');
    quoted.append(value);
    quoted.push_back('"');
    return quoted;
}

void set_qt_ini_value(std::string& contents, std::string_view key, std::string_view value) {
    const std::string prefix = std::string(key) + "=";
    const std::string line = prefix + quote_qt_ini_value(value);

    std::size_t pos = 0;
    while (true) {
        pos = contents.find(prefix, pos);
        if (pos == std::string::npos) {
            if (!contents.empty() && contents.back() != '\n') {
                contents.push_back('\n');
            }
            contents += line;
            contents.push_back('\n');
            return;
        }
        // Only match keys at the start of a line (avoid substring collisions).
        if (pos == 0 || contents[pos - 1] == '\n') {
            break;
        }
        pos += prefix.size();
    }

    const auto end = contents.find('\n', pos);
    if (end == std::string::npos) {
        contents.replace(pos, contents.size() - pos, line);
    } else {
        contents.replace(pos, end - pos, line);
    }
}

void set_qt_ini_group_value(
    std::string& contents,
    std::string_view group,
    std::string_view key,
    std::string_view value) {
    const std::string section_header = "[" + std::string(group) + "]";
    auto section_pos = contents.find(section_header);
    if (section_pos == std::string::npos) {
        if (!contents.empty() && contents.back() != '\n') {
            contents.push_back('\n');
        }
        contents += '\n';
        contents += section_header;
        contents += '\n';
        contents += std::string(key);
        contents += '=';
        contents += quote_qt_ini_value(value);
        contents += '\n';
        return;
    }

    auto body_start = section_pos + section_header.size();
    if (body_start < contents.size() && contents[body_start] == '\r') {
        ++body_start;
    }
    if (body_start < contents.size() && contents[body_start] == '\n') {
        ++body_start;
    }

    const auto next_section = contents.find("\n[", body_start);
    const auto body_end = next_section == std::string::npos ? contents.size() : next_section;
    std::string body = contents.substr(body_start, body_end - body_start);
    set_qt_ini_value(body, key, value);
    contents.replace(body_start, body_end - body_start, body);
}

std::string sdl_button_binding(const std::string& guid, int button) {
    return "pad:0,button:" + std::to_string(button) + ",port:0,guid:" + guid + ",engine:sdl";
}

std::string sdl_axis_trigger_binding(const std::string& guid, int axis) {
    return "threshold:0.500000,axis:" + std::to_string(axis) + ",port:0,guid:" + guid +
        ",invert:+,engine:sdl";
}

std::string sdl_stick_binding(const std::string& guid, int axis_x, int axis_y) {
    return "range:1.000000,deadzone:0.150000,threshold:0.500000,axis_y:" +
        std::to_string(axis_y) + ",axis_x:" + std::to_string(axis_x) +
        ",pad:0,port:0,guid:" + guid + ",engine:sdl";
}

void write_yuzu_sdl_binding_map(
    const std::function<void(std::string_view, std::string_view)>& set,
    const std::string& guid) {
    // Yuzu/SDL enumerates ArchStreamer uinput face buttons as
    // 0=SOUTH(A), 1=EAST(B), 2=WEST(X), 3=NORTH(Y). RetroArch udev uses
    // linux keycode order instead (2=NORTH, 3=WEST) — keep these distinct.
    set("button_a", sdl_button_binding(guid, 0));
    set("button_b", sdl_button_binding(guid, 1));
    set("button_x", sdl_button_binding(guid, 2));
    set("button_y", sdl_button_binding(guid, 3));
    set("button_l", sdl_button_binding(guid, 4));
    set("button_r", sdl_button_binding(guid, 5));
    set("button_minus", sdl_button_binding(guid, 6));
    set("button_plus", sdl_button_binding(guid, 7));
    set("button_home", sdl_button_binding(guid, 8));
    set("button_lstick", sdl_button_binding(guid, 9));
    set("button_rstick", sdl_button_binding(guid, 10));
    set("button_dup", sdl_button_binding(guid, 11));
    set("button_ddown", sdl_button_binding(guid, 12));
    set("button_dleft", sdl_button_binding(guid, 13));
    set("button_dright", sdl_button_binding(guid, 14));
    set("button_sl", sdl_button_binding(guid, 4));
    set("button_sr", sdl_button_binding(guid, 5));
    set("button_zl", sdl_axis_trigger_binding(guid, 2));
    set("button_zr", sdl_axis_trigger_binding(guid, 5));
    set("button_screenshot", "[empty]");
    set("lstick", sdl_stick_binding(guid, 0, 1));
    set("rstick", sdl_stick_binding(guid, 3, 4));
    set("motionleft", "[empty]");
    set("motionright", "[empty]");
    set("type", "0");
}

void write_yuzu_player_sdl_controls(
    std::string& contents,
    int player_index,
    const std::string& guid) {
    const std::string prefix = "player_" + std::to_string(player_index) + "_";
    const auto set = [&](std::string_view suffix, std::string_view value) {
        set_qt_ini_group_value(contents, "Controls", std::string(prefix) + std::string(suffix), value);
        set_qt_ini_group_value(
            contents,
            "Controls",
            std::string(prefix) + std::string(suffix) + "\\default",
            "false");
    };

    write_yuzu_sdl_binding_map(set, guid);
    set("connected", "true");
}

void write_yuzu_input_profile(const std::filesystem::path& path, const std::string& guid) {
    std::string contents = "[Controls]\n";
    const auto set = [&](std::string_view key, std::string_view value) {
        set_qt_ini_value(contents, key, value);
        set_qt_ini_value(contents, std::string(key) + "\\default", "false");
    };
    write_yuzu_sdl_binding_map(set, guid);
    // type\\default stays true in personal PS4.ini; keep bindings marked custom.
    set_qt_ini_value(contents, "type\\default", "true");

    std::filesystem::create_directories(path.parent_path());
    std::ofstream out(path, std::ios::trunc);
    if (!out) {
        throw std::runtime_error("failed to write Yuzu input profile: " + path.string());
    }
    out << contents;
}

void ensure_yuzu_qt_config(
    const YuzuUserProfile& profile,
    bool force_opengl,
    bool force_vulkan,
    int vulkan_device,
    int resolution_scale) {
    const auto config_dir = profile.xdg_config_home / "yuzu";
    const auto config_path = config_dir / "qt-config.ini";
    std::filesystem::create_directories(config_dir);

    const auto yuzu_data = profile.xdg_data_home / "yuzu";
    const auto nand = (yuzu_data / "nand").string();
    const auto sdmc = (yuzu_data / "sdmc").string();
    const auto load = (yuzu_data / "load").string();
    const auto dump = (yuzu_data / "dump").string();
    const auto tas = (yuzu_data / "tas").string();
    std::filesystem::create_directories(yuzu_data / "tas");
    std::filesystem::create_directories(yuzu_data / "screenshots");
    std::filesystem::create_directories(yuzu_data / "nand" / "system" / "Contents" / "registered");
    std::filesystem::create_directories(yuzu_data / "nand" / "user" / "Contents" / "registered");
    std::filesystem::create_directories(yuzu_data / "sdmc" / "Nintendo" / "Contents" / "registered");

    std::string contents;
    if (std::filesystem::exists(config_path)) {
        std::ifstream in(config_path);
        contents.assign(std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>());
    } else {
        // Minimal first-run config: skip telemetry/privacy wizard and pin save paths.
        // Keys must live under the Qt groups Yuzu reads (UI / WebService / Data Storage).
        contents =
            "[Data%20Storage]\n"
            "use_virtual_sd=true\n"
            "use_virtual_sd\\default=true\n"
            "nand_directory=" + nand + "\n"
            "nand_directory\\default=false\n"
            "sdmc_directory=" + sdmc + "\n"
            "sdmc_directory\\default=false\n"
            "load_directory=" + load + "\n"
            "load_directory\\default=false\n"
            "dump_directory=" + dump + "\n"
            "dump_directory\\default=false\n"
            "tas_directory=" + tas + "\n"
            "tas_directory\\default=false\n"
            "\n"
            "[UI]\n"
            "confirmStop=0\n"
            "confirmStop\\default=false\n"
            "firstStart=false\n"
            "firstStart\\default=false\n"
            "calloutFlags=1\n"
            "calloutFlags\\default=false\n"
            "\n"
            "[Renderer]\n"
            "backend=0\n"
            "backend\\default=false\n"
            "\n"
            "[WebService]\n"
            "enable_telemetry=false\n"
            "enable_telemetry\\default=false\n"
            "web_api_url=https://api.yuzu-emu.org\n"
            "web_api_url\\default=true\n"
            "yuzu_token=\n"
            "yuzu_token\\default=true\n"
            "yuzu_username=\n"
            "yuzu_username\\default=true\n";
    }

    // Always force these so a half-created profile from a failed first launch recovers.
    set_qt_ini_value(contents, "nand_directory", nand);
    set_qt_ini_value(contents, "nand_directory\\default", "false");
    set_qt_ini_value(contents, "sdmc_directory", sdmc);
    set_qt_ini_value(contents, "sdmc_directory\\default", "false");
    set_qt_ini_value(contents, "load_directory", load);
    set_qt_ini_value(contents, "load_directory\\default", "false");
    set_qt_ini_value(contents, "dump_directory", dump);
    set_qt_ini_value(contents, "dump_directory\\default", "false");
    set_qt_ini_value(contents, "tas_directory", tas);
    set_qt_ini_value(contents, "tas_directory\\default", "false");
    set_qt_ini_value(contents, "firstStart", "false");
    set_qt_ini_value(contents, "firstStart\\default", "false");
    // Telemetry callout bit (0x1): pretends the consent dialog was already answered.
    set_qt_ini_value(contents, "calloutFlags", "1");
    set_qt_ini_value(contents, "calloutFlags\\default", "false");
    set_qt_ini_value(contents, "enable_telemetry", "false");
    set_qt_ini_value(contents, "enable_telemetry\\default", "false");
    set_qt_ini_value(contents, "confirmStop", "0");
    if (force_opengl) {
        // 0 = OpenGL, 1 = Vulkan. Virtual capture displays often cannot present Vulkan.
        set_qt_ini_group_value(contents, "Renderer", "backend", "0");
        set_qt_ini_group_value(contents, "Renderer", "backend\\default", "false");
        set_qt_ini_group_value(contents, "Renderer", "shader_backend", "0");
        set_qt_ini_group_value(contents, "Renderer", "shader_backend\\default", "false");
        set_qt_ini_group_value(contents, "Renderer", "perform_vulkan_check", "false");
        set_qt_ini_group_value(contents, "Renderer", "perform_vulkan_check\\default", "false");
        // Exclusive fullscreen is unreliable on Xvfb (tiny/centered black window).
        // Host launches with -geometry WxH+0+0 to fill the capture surface instead.
        set_qt_ini_group_value(contents, "UI", "fullscreen", "false");
        set_qt_ini_group_value(contents, "UI", "fullscreen\\default", "false");
    } else if (force_vulkan) {
        // Gamescope presents Vulkan cleanly; a leftover OpenGL backend from VirtualGL
        // sessions can leave the PipeWire stream blank.
        set_qt_ini_group_value(contents, "Renderer", "backend", "1");
        set_qt_ini_group_value(contents, "Renderer", "backend\\default", "false");
        set_qt_ini_group_value(contents, "Renderer", "perform_vulkan_check", "false");
        set_qt_ini_group_value(contents, "Renderer", "perform_vulkan_check\\default", "false");
    }
    if (vulkan_device >= 0) {
        // Yuzu sorts devices (discrete NVIDIA first, name descending) — not vulkaninfo order.
        set_qt_ini_group_value(
            contents, "Renderer", "vulkan_device", std::to_string(vulkan_device));
        set_qt_ini_group_value(contents, "Renderer", "vulkan_device\\default", "false");
    }
    if (resolution_scale > 0) {
        // ResolutionSetup: Res1X=2, Res2X=3, … Res6X=7
        const int scale = std::clamp(resolution_scale, 1, 6);
        const int setup = scale + 1;
        set_qt_ini_group_value(
            contents, "Renderer", "resolution_setup", std::to_string(setup));
        set_qt_ini_group_value(contents, "Renderer", "resolution_setup\\default", "false");
    }

    std::ofstream out(config_path, std::ios::trunc);
    if (!out) {
        throw std::runtime_error("failed to write Yuzu qt-config.ini: " + config_path.string());
    }
    out << contents;
}


std::optional<std::filesystem::path> find_source_appimage() {
    if (const auto env = path_from_env("ARCHSTREAMER_YUZU"); env.has_value()) {
        if (std::filesystem::is_regular_file(*env)) {
            return env;
        }
    }
    if (const auto env = path_from_env("YUZU_APPIMAGE"); env.has_value()) {
        if (std::filesystem::is_regular_file(*env)) {
            return env;
        }
    }
    if (const auto env = path_from_env("YUZU_BIN"); env.has_value()) {
        if (std::filesystem::is_regular_file(*env)) {
            return env;
        }
    }

    const auto home = home_dir();
#ifdef _WIN32
    const auto local = archstreamer_cache_directory();
    const std::vector<std::filesystem::path> candidates{
        std::filesystem::path{local} / "yuzu" / "yuzu.exe",
        home / "Downloads" / "Yuzu_WIN" / "yuzu-windows-msvc" / "yuzu.exe",
        home / "Downloads" / "yuzu-windows-msvc" / "yuzu.exe",
        home / "AppData" / "Local" / "yuzu" / "yuzu.exe",
    };
    for (const auto& candidate : candidates) {
        if (std::filesystem::is_regular_file(candidate)) {
            return candidate;
        }
        // Directory containing yuzu.exe
        if (std::filesystem::is_directory(candidate.parent_path())) {
            const auto exe = candidate.parent_path() / "yuzu.exe";
            if (std::filesystem::is_regular_file(exe)) {
                return exe;
            }
        }
    }
    // If ARCHSTREAMER_YUZU points at a directory of the MSVC build:
    if (const auto env = path_from_env("ARCHSTREAMER_YUZU"); env.has_value()) {
        if (std::filesystem::is_directory(*env)) {
            for (const char* name : {"yuzu.exe", "yuzu-cmd.exe"}) {
                const auto exe = *env / name;
                if (std::filesystem::is_regular_file(exe)) {
                    return exe;
                }
            }
        }
    }
#else
    const std::vector<std::filesystem::path> candidates{
        "/srv/emus/Switch/yuzu.AppImage",
        "/srv/emus/Switch/yuzu-20231111-030c140c0.AppImage",
        home / "Applications/yuzu.AppImage",
        home / ".local/bin/yuzu",
        "/usr/local/bin/yuzu",
        "/usr/bin/yuzu",
    };

    for (const auto& candidate : candidates) {
        if (!std::filesystem::exists(candidate)) {
            continue;
        }
        if (std::filesystem::is_regular_file(candidate)) {
            const auto name = candidate.filename().string();
            if (candidate.extension() == ".AppImage" || name == "yuzu" || name.find("yuzu") != std::string::npos) {
                return candidate;
            }
            return candidate;
        }
        if (std::filesystem::is_directory(candidate)) {
            for (const auto& entry : std::filesystem::directory_iterator(candidate)) {
                if (!entry.is_regular_file()) {
                    continue;
                }
                const auto path = entry.path();
                if (path.extension() == ".AppImage" || path.filename() == "yuzu") {
                    return path;
                }
            }
        }
    }
#endif
    return std::nullopt;
}

std::optional<std::filesystem::path> find_source_keys_dir() {
    if (const auto env = path_from_env("ARCHSTREAMER_YUZU_KEYS"); env.has_value()) {
        if (std::filesystem::is_directory(*env)) {
            return env;
        }
    }
    const auto home = home_dir();
    const std::vector<std::filesystem::path> candidates{
#ifdef _WIN32
        home / "AppData" / "Roaming" / "yuzu" / "keys",
        std::filesystem::path{archstreamer_cache_directory()} / "yuzu" / "keys",
#else
        home / ".local/share/yuzu/keys",
        home / ".config/yuzu/keys",
        "/srv/retroarch/system/yuzu/keys",
        "/srv/retroarch/system/keys",
#endif
    };
    for (const auto& candidate : candidates) {
        if (std::filesystem::is_regular_file(candidate / "prod.keys")) {
            return candidate;
        }
    }
    return std::nullopt;
}

std::optional<std::filesystem::path> find_source_ryujinx() {
    if (const auto env = path_from_env("ARCHSTREAMER_RYUJINX"); env.has_value()) {
        if (std::filesystem::is_regular_file(*env)) {
            return env;
        }
        if (std::filesystem::is_directory(*env)) {
#ifdef _WIN32
            for (const char* name : {"Ryujinx.exe", "ryujinx.exe"}) {
#else
            for (const char* name : {"Ryujinx", "ryujinx", "Ryujinx.AppImage", "ryujinx.AppImage"}) {
#endif
                const auto exe = *env / name;
                if (std::filesystem::is_regular_file(exe)) {
                    return exe;
                }
            }
        }
    }

    const auto home = home_dir();
#ifdef _WIN32
    const auto local = archstreamer_cache_directory();
    const std::vector<std::filesystem::path> candidates{
        std::filesystem::path{local} / "ryujinx" / "Ryujinx.exe",
        home / "Downloads" / "Ryujinx" / "Ryujinx.exe",
        home / "AppData" / "Local" / "Ryujinx" / "Ryujinx.exe",
    };
#else
    const std::vector<std::filesystem::path> candidates{
        "/srv/emus/Switch/Ryujinx",
        "/srv/emus/Switch/ryujinx",
        "/srv/emus/Switch/Ryujinx.AppImage",
        home / "Applications/Ryujinx.AppImage",
        home / "Applications/Ryujinx",
        home / ".local/bin/Ryujinx",
        home / ".local/bin/ryujinx",
        "/usr/local/bin/Ryujinx",
        "/usr/local/bin/ryujinx",
        "/usr/bin/Ryujinx",
        "/usr/bin/ryujinx",
    };
#endif
    for (const auto& candidate : candidates) {
        if (std::filesystem::is_regular_file(candidate)) {
            return candidate;
        }
    }
    return std::nullopt;
}

} // namespace

std::filesystem::path default_yuzu_runtime_root() {
    if (const auto home = home_dir(); !home.empty()) {
#ifdef _WIN32
        // %LOCALAPPDATA%\archstreamer\yuzu
        const auto cache = archstreamer_cache_directory();
        if (!cache.empty()) {
            return std::filesystem::path{cache} / "yuzu";
        }
        return home / "AppData" / "Local" / "archstreamer" / "yuzu";
#else
        return home / ".local/share/archstreamer/yuzu";
#endif
    }
    return std::filesystem::current_path() / "archstreamer-yuzu";
}

bool yuzu_runtime_available() {
#ifdef _WIN32
    const auto managed_binary = default_yuzu_runtime_root() / "yuzu.exe";
#else
    const auto managed_binary = default_yuzu_runtime_root() / "yuzu.AppImage";
#endif
    if (std::filesystem::is_regular_file(managed_binary)) {
        return true;
    }
    return find_source_appimage().has_value();
}

std::string yuzu_unavailable_message() {
    const auto root = default_yuzu_runtime_root();
#ifdef _WIN32
    return "Yuzu runtime not found. Switch titles require yuzu.exe under " + root.string() +
           " (or set ARCHSTREAMER_YUZU to a yuzu-windows-msvc build). "
           "Nintendo Switch games will not be listed until Yuzu is installed.";
#else
    return "Yuzu runtime not found. Switch titles require yuzu.AppImage under " + root.string() +
           " (or set ARCHSTREAMER_YUZU). "
           "Nintendo Switch games will not be listed until Yuzu is installed.";
#endif
}

std::optional<ResolvedStandaloneEmulator> ensure_yuzu_runtime() {
    const auto root = default_yuzu_runtime_root();
#ifdef _WIN32
    const auto managed_binary = root / "yuzu.exe";
#else
    const auto managed_binary = root / "yuzu.AppImage";
#endif
    const auto managed_keys = root / "keys";
    std::filesystem::create_directories(root);
    std::filesystem::create_directories(managed_keys);

    if (!std::filesystem::exists(managed_binary)) {
        const auto source = find_source_appimage();
        if (!source.has_value()) {
            return std::nullopt;
        }
#ifdef _WIN32
        const auto source_dir = source->parent_path();
        std::cout << "Installing Yuzu Windows build into " << root << " (from " << source_dir << ")\n";
        for (const auto& entry : std::filesystem::directory_iterator(source_dir)) {
            const auto name = entry.path().filename();
            if (name == "plugins" || name == "mediaservice") {
                std::filesystem::copy(
                    entry.path(),
                    root / name,
                    std::filesystem::copy_options::recursive |
                        std::filesystem::copy_options::overwrite_existing);
                continue;
            }
            if (!entry.is_regular_file()) {
                continue;
            }
            std::filesystem::copy_file(
                entry.path(),
                root / name,
                std::filesystem::copy_options::overwrite_existing);
        }
#else
        std::cout << "Installing Yuzu AppImage into " << managed_binary << " (from " << *source << ")\n";
        std::filesystem::copy_file(*source, managed_binary, std::filesystem::copy_options::overwrite_existing);
        std::filesystem::permissions(
            managed_binary,
            std::filesystem::perms::owner_all | std::filesystem::perms::group_read |
                std::filesystem::perms::group_exec | std::filesystem::perms::others_read |
                std::filesystem::perms::others_exec,
            std::filesystem::perm_options::replace);
#endif
    }

    if (!std::filesystem::exists(managed_keys / "prod.keys")) {
        if (const auto source_keys = find_source_keys_dir(); source_keys.has_value()) {
            std::cout << "Installing Yuzu keys into " << managed_keys << " (from " << *source_keys << ")\n";
            copy_key_files(*source_keys, managed_keys);
        } else {
            std::cerr
                << "Warning: Yuzu prod.keys not found. Place keys in " << managed_keys
                << " or set ARCHSTREAMER_YUZU_KEYS.\n";
        }
    } else {
        if (const auto source_keys = find_source_keys_dir(); source_keys.has_value()) {
            copy_key_files(*source_keys, managed_keys);
        }
    }

    if (!std::filesystem::is_regular_file(managed_binary)) {
        return std::nullopt;
    }

    return ResolvedStandaloneEmulator{
        managed_binary,
        {"-f", "-g"},
        "Yuzu",
    };
}

YuzuUserProfile prepare_yuzu_user_profile(
    const SaveProfile& save_profile,
    bool force_opengl,
    bool force_vulkan,
    int vulkan_device,
    int resolution_scale) {
    YuzuUserProfile profile;
    // Isolate Qt/Yuzu paths per ArchStreamer save user.
    profile.xdg_data_home = save_profile.user_directory / "yuzu" / "xdg-data";
    profile.xdg_config_home = save_profile.user_directory / "yuzu" / "xdg-config";
    profile.keys_directory = profile.xdg_data_home / "yuzu" / "keys";

    std::filesystem::create_directories(profile.xdg_data_home / "yuzu");
    std::filesystem::create_directories(profile.xdg_config_home / "yuzu");
    std::filesystem::create_directories(profile.keys_directory);
    // Common save-related trees Yuzu may create; ensure parents exist.
    std::filesystem::create_directories(profile.xdg_data_home / "yuzu" / "nand");
    std::filesystem::create_directories(profile.xdg_data_home / "yuzu" / "sdmc");
    std::filesystem::create_directories(profile.xdg_data_home / "yuzu" / "load");
    std::filesystem::create_directories(profile.xdg_data_home / "yuzu" / "screenshot");
    std::filesystem::create_directories(profile.xdg_data_home / "yuzu" / "dump");

    const auto shared_keys = default_yuzu_runtime_root() / "keys";
    copy_key_files(shared_keys, profile.keys_directory);

    // Also seed from the host user's personal Yuzu install when shared keys were empty.
    if (!std::filesystem::exists(profile.keys_directory / "prod.keys")) {
        if (const auto source_keys = find_source_keys_dir(); source_keys.has_value()) {
            copy_key_files(*source_keys, profile.keys_directory);
        }
    }

    ensure_yuzu_qt_config(profile, force_opengl, force_vulkan, vulkan_device, resolution_scale);
    return profile;
}

void configure_yuzu_archstreamer_controls(
    const YuzuUserProfile& profile,
    const std::vector<std::string>& sdl_guids) {
    if (sdl_guids.empty()) {
        std::cerr << "Warning: no ArchStreamer SDL GUIDs; Yuzu Controls left unchanged.\n";
        return;
    }

    const auto config_dir = profile.xdg_config_home / "yuzu";
    const auto config_path = config_dir / "qt-config.ini";
    const auto input_dir = config_dir / "input";
    std::filesystem::create_directories(input_dir);

    std::string contents;
    if (std::filesystem::exists(config_path)) {
        std::ifstream in(config_path);
        contents.assign(std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>());
    }
    if (contents.empty()) {
        ensure_yuzu_qt_config(profile, false, false, -1, 0);
        std::ifstream in(config_path);
        contents.assign(std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>());
    }

    set_qt_ini_group_value(contents, "Controls", "keyboard_enabled", "false");
    set_qt_ini_group_value(contents, "Controls", "keyboard_enabled\\default", "false");

    // Yuzu clears the SDL name-CRC (GUID bytes 2-3) before matching. Normalize here too
    // so callers that pass raw SDL_JoystickGetGUIDString values still work.
    const auto filter_guid = [](std::string guid) {
        if (guid.size() >= 8) {
            guid.replace(4, 4, "0000");
        }
        return guid;
    };

    for (std::size_t i = 0; i < sdl_guids.size() && i < 8; ++i) {
        if (sdl_guids[i].empty()) {
            continue;
        }
        const auto guid = filter_guid(sdl_guids[i]);
        // Same layout as ~/.config/yuzu/input/PS4.ini — selectable profiles plus active bindings.
        const auto profile_name =
            i == 0 ? std::string("ArchStreamer") : ("ArchStreamer_P" + std::to_string(i + 1));
        write_yuzu_input_profile(input_dir / (profile_name + ".ini"), guid);
        write_yuzu_player_sdl_controls(contents, static_cast<int>(i), guid);
    }

    std::ofstream out(config_path, std::ios::trunc);
    if (!out) {
        throw std::runtime_error("failed to write Yuzu Controls: " + config_path.string());
    }
    out << contents;
    std::cout
        << "Yuzu Controls: bound " << sdl_guids.size()
        << " ArchStreamer pad(s) via SDL GUID (+ input/ profile)\n";
}

std::vector<std::pair<std::string, std::string>> yuzu_launch_environment(
    const YuzuUserProfile& profile) {
    return {
        {"XDG_DATA_HOME", profile.xdg_data_home.string()},
        {"XDG_CONFIG_HOME", profile.xdg_config_home.string()},
        // gamescope headless often leaves the child without "focus"; without this SDL may
        // stop delivering joystick updates and Yuzu sees intermittent pad input.
        {"SDL_JOYSTICK_ALLOW_BACKGROUND_EVENTS", "1"},
    };
}

std::filesystem::path default_ryujinx_runtime_root() {
    if (const auto home = home_dir(); !home.empty()) {
#ifdef _WIN32
        const auto cache = archstreamer_cache_directory();
        if (!cache.empty()) {
            return std::filesystem::path{cache} / "ryujinx";
        }
        return home / "AppData" / "Local" / "archstreamer" / "ryujinx";
#else
        return home / ".local/share/archstreamer/ryujinx";
#endif
    }
    return std::filesystem::current_path() / "archstreamer-ryujinx";
}

bool ryujinx_runtime_available() {
#ifdef _WIN32
    const auto managed_binary = default_ryujinx_runtime_root() / "Ryujinx.exe";
#else
    const auto managed_binary = default_ryujinx_runtime_root() / "Ryujinx";
    const auto managed_appimage = default_ryujinx_runtime_root() / "Ryujinx.AppImage";
    if (std::filesystem::is_regular_file(managed_appimage)) {
        return true;
    }
#endif
    if (std::filesystem::is_regular_file(managed_binary)) {
        return true;
    }
    return find_source_ryujinx().has_value();
}

std::string ryujinx_unavailable_message() {
    const auto root = default_ryujinx_runtime_root();
#ifdef _WIN32
    return "Ryujinx runtime not found. Place Ryujinx.exe under " + root.string() +
           " (or set ARCHSTREAMER_RYUJINX). Link backends that need Ryujinx will stay unavailable.";
#else
    return "Ryujinx runtime not found. Place Ryujinx under " + root.string() +
           " (or set ARCHSTREAMER_RYUJINX). Link backends that need Ryujinx will stay unavailable.";
#endif
}

std::optional<ResolvedStandaloneEmulator> ensure_ryujinx_runtime() {
    const auto root = default_ryujinx_runtime_root();
    const auto keys_dir = root / "keys";
#ifdef _WIN32
    const auto managed_binary = root / "Ryujinx.exe";
#else
    auto managed_binary = root / "Ryujinx";
    const auto managed_appimage = root / "Ryujinx.AppImage";
#endif
    std::filesystem::create_directories(root);
    std::filesystem::create_directories(keys_dir);

#ifdef _WIN32
    if (!std::filesystem::exists(managed_binary)) {
#else
    if (!std::filesystem::exists(managed_binary) && !std::filesystem::exists(managed_appimage)) {
#endif
        const auto source = find_source_ryujinx();
        if (!source.has_value()) {
            return std::nullopt;
        }
#ifdef _WIN32
        const auto source_dir = source->parent_path();
        std::cout << "Installing Ryujinx Windows build into " << root << " (from " << source_dir << ")\n";
        for (const auto& entry : std::filesystem::directory_iterator(source_dir)) {
            if (!entry.is_regular_file() && !entry.is_directory()) {
                continue;
            }
            const auto name = entry.path().filename();
            if (entry.is_directory()) {
                std::filesystem::copy(
                    entry.path(),
                    root / name,
                    std::filesystem::copy_options::recursive |
                        std::filesystem::copy_options::skip_existing);
            } else {
                std::filesystem::copy_file(
                    entry.path(),
                    root / name,
                    std::filesystem::copy_options::skip_existing);
            }
        }
#else
        const auto destination =
            (source->extension() == ".AppImage") ? managed_appimage : managed_binary;
        std::cout << "Installing Ryujinx into " << destination << " (from " << *source << ")\n";
        std::filesystem::copy_file(*source, destination, std::filesystem::copy_options::overwrite_existing);
        std::filesystem::permissions(
            destination,
            std::filesystem::perms::owner_all | std::filesystem::perms::group_read |
                std::filesystem::perms::group_exec | std::filesystem::perms::others_read |
                std::filesystem::perms::others_exec,
            std::filesystem::perm_options::replace);
        managed_binary = destination;
#endif
    }

    // Prefer Yuzu managed keys, then personal installs.
    copy_key_files(default_yuzu_runtime_root() / "keys", keys_dir);
    if (!std::filesystem::is_regular_file(keys_dir / "prod.keys")) {
        if (const auto source_keys = find_source_keys_dir(); source_keys.has_value()) {
            copy_key_files(*source_keys, keys_dir);
        }
    }

#ifdef _WIN32
    if (!std::filesystem::is_regular_file(managed_binary)) {
        return std::nullopt;
    }
    return ResolvedStandaloneEmulator{managed_binary, {"--fullscreen"}, "Ryujinx"};
#else
    if (std::filesystem::is_regular_file(managed_appimage)) {
        return ResolvedStandaloneEmulator{managed_appimage, {"--fullscreen"}, "Ryujinx"};
    }
    if (std::filesystem::is_regular_file(managed_binary)) {
        return ResolvedStandaloneEmulator{managed_binary, {"--fullscreen"}, "Ryujinx"};
    }
    if (const auto source = find_source_ryujinx(); source.has_value()) {
        return ResolvedStandaloneEmulator{*source, {"--fullscreen"}, "Ryujinx"};
    }
    return std::nullopt;
#endif
}

std::optional<ResolvedStandaloneEmulator> resolve_switch_runtime() {
    if (ryujinx_runtime_available()) {
        return ensure_ryujinx_runtime();
    }
    if (yuzu_runtime_available()) {
        return ensure_yuzu_runtime();
    }
    return std::nullopt;
}

std::string switch_runtime_unavailable_message() {
    return "No Switch emulator found. Install Ryujinx (preferred) under " +
        default_ryujinx_runtime_root().string() +
        " or Yuzu under " + default_yuzu_runtime_root().string() +
        " (or set ARCHSTREAMER_RYUJINX / ARCHSTREAMER_YUZU).";
}

namespace {

void upsert_json_number(std::string& json, const std::string& key, int value) {
    const std::string needle = "\"" + key + "\"";
    const auto pos = json.find(needle);
    if (pos == std::string::npos) {
        // Insert before final closing brace.
        const auto brace = json.rfind('}');
        if (brace == std::string::npos) {
            return;
        }
        std::string insert = "  \"" + key + "\": " + std::to_string(value) + ",\n";
        json.insert(brace, insert);
        return;
    }
    const auto colon = json.find(':', pos);
    if (colon == std::string::npos) {
        return;
    }
    auto start = colon + 1;
    while (start < json.size() && (json[start] == ' ' || json[start] == '\t')) {
        ++start;
    }
    auto end = start;
    while (end < json.size() && (std::isdigit(static_cast<unsigned char>(json[end])) || json[end] == '-')) {
        ++end;
    }
    json.replace(start, end - start, std::to_string(value));
}

void upsert_json_bool(std::string& json, const std::string& key, bool value) {
    const std::string needle = "\"" + key + "\"";
    const auto pos = json.find(needle);
    const char* lit = value ? "true" : "false";
    if (pos == std::string::npos) {
        const auto brace = json.rfind('}');
        if (brace == std::string::npos) {
            return;
        }
        json.insert(brace, std::string("  \"") + key + "\": " + lit + ",\n");
        return;
    }
    const auto colon = json.find(':', pos);
    if (colon == std::string::npos) {
        return;
    }
    auto start = colon + 1;
    while (start < json.size() && (json[start] == ' ' || json[start] == '\t')) {
        ++start;
    }
    auto end = start;
    while (end < json.size() && std::isalpha(static_cast<unsigned char>(json[end]))) {
        ++end;
    }
    json.replace(start, end - start, lit);
}

void ensure_ryujinx_config(
    const std::filesystem::path& config_path,
    bool enable_ldn_mitm,
    int resolution_scale) {
    std::filesystem::create_directories(config_path.parent_path());
    std::string contents;
    if (std::filesystem::is_regular_file(config_path)) {
        std::ifstream in(config_path);
        contents.assign(std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>());
    }
    if (contents.empty()) {
        contents = "{\n}\n";
    }
    // 0=Disabled, 1=LdnRyu, 2=LdnMitm (same-network / same-host Link).
    upsert_json_number(contents, "multiplayer_mode", enable_ldn_mitm ? 2 : 1);
    upsert_json_bool(contents, "enable_internet_access", false);
    upsert_json_bool(contents, "enable_vsync", true);
    upsert_json_number(contents, "dram_size", 3); // 12 GiB
    if (resolution_scale > 0) {
        upsert_json_number(contents, "res_scale", std::clamp(resolution_scale, 1, 4));
    }
    std::ofstream out(config_path, std::ios::trunc);
    if (!out) {
        throw std::runtime_error("failed to write Ryujinx Config.json: " + config_path.string());
    }
    out << contents;
}

} // namespace

RyujinxUserProfile prepare_ryujinx_user_profile(
    const SaveProfile& save_profile,
    bool enable_ldn_mitm,
    int resolution_scale) {
    RyujinxUserProfile profile;
    profile.xdg_config_home = save_profile.user_directory / "ryujinx" / "xdg-config";
    profile.data_root = profile.xdg_config_home / "Ryujinx";
    profile.keys_directory = profile.data_root / "system";

    std::filesystem::create_directories(profile.data_root / "bis" / "user" / "save");
    std::filesystem::create_directories(profile.keys_directory);
    std::filesystem::create_directories(save_profile.user_directory / "switch" / "saves");

    copy_key_files(default_ryujinx_runtime_root() / "keys", profile.keys_directory);
    if (!std::filesystem::is_regular_file(profile.keys_directory / "prod.keys")) {
        copy_key_files(default_yuzu_runtime_root() / "keys", profile.keys_directory);
    }
    if (!std::filesystem::is_regular_file(profile.keys_directory / "prod.keys")) {
        if (const auto source_keys = find_source_keys_dir(); source_keys.has_value()) {
            copy_key_files(*source_keys, profile.keys_directory);
        }
    }

    ensure_ryujinx_config(
        profile.data_root / "Config.json",
        enable_ldn_mitm,
        resolution_scale);
    return profile;
}

std::vector<std::pair<std::string, std::string>> ryujinx_launch_environment(
    const RyujinxUserProfile& profile) {
    return {
        {"XDG_CONFIG_HOME", profile.xdg_config_home.string()},
        {"SDL_JOYSTICK_ALLOW_BACKGROUND_EVENTS", "1"},
    };
}

} // namespace archstreamer
