#include "host/standalone_emulator.hpp"

#include "common/platform/paths.hpp"

#include <nlohmann/json.hpp>

#include <algorithm>
#include <cctype>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <functional>
#include <iostream>
#include <iterator>
#include <stdexcept>
#include <string>
#include <string_view>
#include <system_error>
#include <vector>

namespace archstreamer {
namespace {

std::optional<std::filesystem::path> path_from_env(std::string_view key) {
    if (const char* value = std::getenv(std::string(key).c_str()); value != nullptr && *value != '\0') {
        return std::filesystem::path{value};
    }
    return std::nullopt;
}

std::filesystem::path home_dir() {
    if (const auto home = user_home_directory(); !home.empty()) {
        return home;
    }
    if (const char* home = std::getenv("HOME"); home != nullptr && *home != '\0') {
        return home;
    }
    return {};
}

void copy_file_if_missing(const std::filesystem::path& source, const std::filesystem::path& destination) {
    if (!std::filesystem::is_regular_file(source)) {
        return;
    }
    if (std::filesystem::exists(destination)) {
        return;
    }
    std::filesystem::create_directories(destination.parent_path());
    std::filesystem::copy_file(source, destination, std::filesystem::copy_options::skip_existing);
}

void copy_key_files(const std::filesystem::path& source_dir, const std::filesystem::path& destination_dir) {
    if (!std::filesystem::is_directory(source_dir)) {
        return;
    }
    std::filesystem::create_directories(destination_dir);
    for (const auto& name : {"prod.keys", "title.keys", "key_retail.bin", "title.keys_autogenerated"}) {
        copy_file_if_missing(source_dir / name, destination_dir / name);
    }
}

bool directory_has_entries(const std::filesystem::path& path) {
    std::error_code ec;
    if (!std::filesystem::is_directory(path, ec)) {
        return false;
    }
    const auto it = std::filesystem::directory_iterator(path, ec);
    return !ec && it != std::filesystem::directory_iterator{};
}

std::optional<std::filesystem::path> find_source_keys_dir();

void copy_directory_recursive_skip_existing(
    const std::filesystem::path& source,
    const std::filesystem::path& destination) {
    std::filesystem::create_directories(destination);
    for (const auto& entry : std::filesystem::recursive_directory_iterator(source)) {
        const auto relative = std::filesystem::relative(entry.path(), source);
        const auto target = destination / relative;
        if (entry.is_directory()) {
            std::filesystem::create_directories(target);
            continue;
        }
        if (!entry.is_regular_file() && !entry.is_symlink()) {
            continue;
        }
        std::filesystem::create_directories(target.parent_path());
        std::error_code ec;
        std::filesystem::copy(
            entry.path(),
            target,
            std::filesystem::copy_options::skip_existing |
                std::filesystem::copy_options::copy_symlinks,
            ec);
    }
}

std::filesystem::path managed_ryujinx_firmware_registered() {
    return switch_system_defaults_root() / "firmware" / "registered";
}

std::filesystem::path switch_system_keys_directory() {
    return switch_system_defaults_root() / "keys";
}

std::vector<std::filesystem::path> ryujinx_firmware_source_candidates() {
    std::vector<std::filesystem::path> out;
    out.push_back(managed_ryujinx_firmware_registered());
    // Legacy ArchStreamer locations (pre system/switch layout).
    out.push_back(default_ryujinx_runtime_root() / "firmware" / "registered");
    // One-time bootstrap only — never the long-term source of truth.
    if (const auto home = home_dir(); !home.empty()) {
        out.push_back(home / ".config" / "Ryujinx" / "bis" / "system" / "Contents" / "registered");
#ifdef _WIN32
        if (const char* local = std::getenv("LOCALAPPDATA"); local != nullptr && *local != '\0') {
            out.push_back(
                std::filesystem::path{local} / "Ryujinx" / "bis" / "system" / "Contents" / "registered");
        }
#endif
    }
    return out;
}

std::vector<std::filesystem::path> switch_keys_source_candidates() {
    std::vector<std::filesystem::path> out;
    out.push_back(switch_system_keys_directory());
    out.push_back(default_ryujinx_runtime_root() / "keys");
    out.push_back(default_yuzu_runtime_root() / "keys");
    if (const auto source = find_source_keys_dir(); source.has_value()) {
        out.push_back(*source);
    }
    return out;
}

/** Ensure ~/.local/share/archstreamer/system/switch/{keys,firmware} is populated. */
void ensure_switch_system_defaults() {
    const auto keys_dir = switch_system_keys_directory();
    std::filesystem::create_directories(keys_dir);
    if (!std::filesystem::is_regular_file(keys_dir / "prod.keys")) {
        for (const auto& source : switch_keys_source_candidates()) {
            if (source == keys_dir) {
                continue;
            }
            copy_key_files(source, keys_dir);
            if (std::filesystem::is_regular_file(keys_dir / "prod.keys")) {
                std::cout << "Switch keys: installed into " << keys_dir << " (from " << source << ")\n";
                break;
            }
        }
    }

    const auto firmware = managed_ryujinx_firmware_registered();
    if (directory_has_entries(firmware)) {
        return;
    }
    for (const auto& source : ryujinx_firmware_source_candidates()) {
        if (source == firmware || !directory_has_entries(source)) {
            continue;
        }
        // Don't copy through a symlink that already points at the destination.
        std::error_code ec;
        if (std::filesystem::equivalent(source, firmware, ec)) {
            continue;
        }
        std::cout << "Switch firmware: installing into " << firmware << " (from " << source << ")\n";
        copy_directory_recursive_skip_existing(source, firmware);
        if (directory_has_entries(firmware)) {
            return;
        }
    }
}

/** Shared firmware NCAs under ArchStreamer system/switch (seeded once). */
std::filesystem::path ensure_managed_ryujinx_firmware() {
    ensure_switch_system_defaults();
    return managed_ryujinx_firmware_registered();
}

/** Ensure the per-user Ryujinx profile can see system firmware (avoids "Firmware not found"). */
void ensure_ryujinx_firmware(const std::filesystem::path& data_root) {
    const auto profile_registered =
        data_root / "bis" / "system" / "Contents" / "registered";
    if (directory_has_entries(profile_registered)) {
        return;
    }

    const auto managed = ensure_managed_ryujinx_firmware();
    if (!directory_has_entries(managed)) {
        std::cout << "Warning: Switch firmware not found under "
                  << managed
                  << ". Place firmware NCAs there (or bootstrap once from a desktop Ryujinx "
                     "install).\n";
        std::filesystem::create_directories(profile_registered);
        return;
    }

    std::error_code ec;
    if (std::filesystem::exists(profile_registered, ec)) {
        // Empty placeholder dir from an earlier session — replace with a link/copy.
        std::filesystem::remove_all(profile_registered, ec);
    }
    std::filesystem::create_directories(profile_registered.parent_path());

#ifndef _WIN32
    std::filesystem::create_directory_symlink(managed, profile_registered, ec);
    if (!ec && directory_has_entries(profile_registered)) {
        std::cout << "Ryujinx firmware: linked " << profile_registered << " -> " << managed << '\n';
        return;
    }
    ec.clear();
    if (std::filesystem::exists(profile_registered)) {
        std::filesystem::remove_all(profile_registered, ec);
    }
#endif
    copy_directory_recursive_skip_existing(managed, profile_registered);
    std::cout << "Ryujinx firmware: seeded " << profile_registered << '\n';
}

// Yuzu/QSettings: unquoted commas truncate values (bindings become just "pad:0").
std::string quote_qt_ini_value(std::string_view value) {
    if (value == "[empty]") {
        return "[empty]";
    }
    const bool needs_quotes =
        value.find_first_of(",;\"\n\r") != std::string_view::npos;
    if (!needs_quotes) {
        return std::string(value);
    }
    std::string quoted;
    quoted.reserve(value.size() + 2);
    quoted.push_back('"');
    quoted.append(value);
    quoted.push_back('"');
    return quoted;
}

void set_qt_ini_value(std::string& contents, std::string_view key, std::string_view value) {
    const std::string prefix = std::string(key) + "=";
    const std::string line = prefix + quote_qt_ini_value(value);

    std::size_t pos = 0;
    while (true) {
        pos = contents.find(prefix, pos);
        if (pos == std::string::npos) {
            if (!contents.empty() && contents.back() != '\n') {
                contents.push_back('\n');
            }
            contents += line;
            contents.push_back('\n');
            return;
        }
        // Only match keys at the start of a line (avoid substring collisions).
        if (pos == 0 || contents[pos - 1] == '\n') {
            break;
        }
        pos += prefix.size();
    }

    const auto end = contents.find('\n', pos);
    if (end == std::string::npos) {
        contents.replace(pos, contents.size() - pos, line);
    } else {
        contents.replace(pos, end - pos, line);
    }
}

void set_qt_ini_group_value(
    std::string& contents,
    std::string_view group,
    std::string_view key,
    std::string_view value) {
    const std::string section_header = "[" + std::string(group) + "]";
    auto section_pos = contents.find(section_header);
    if (section_pos == std::string::npos) {
        if (!contents.empty() && contents.back() != '\n') {
            contents.push_back('\n');
        }
        contents += '\n';
        contents += section_header;
        contents += '\n';
        contents += std::string(key);
        contents += '=';
        contents += quote_qt_ini_value(value);
        contents += '\n';
        return;
    }

    auto body_start = section_pos + section_header.size();
    if (body_start < contents.size() && contents[body_start] == '\r') {
        ++body_start;
    }
    if (body_start < contents.size() && contents[body_start] == '\n') {
        ++body_start;
    }

    const auto next_section = contents.find("\n[", body_start);
    const auto body_end = next_section == std::string::npos ? contents.size() : next_section;
    std::string body = contents.substr(body_start, body_end - body_start);
    set_qt_ini_value(body, key, value);
    contents.replace(body_start, body_end - body_start, body);
}

std::string sdl_button_binding(const std::string& guid, int button) {
    return "pad:0,button:" + std::to_string(button) + ",port:0,guid:" + guid + ",engine:sdl";
}

std::string sdl_axis_trigger_binding(const std::string& guid, int axis) {
    return "threshold:0.500000,axis:" + std::to_string(axis) + ",port:0,guid:" + guid +
        ",invert:+,engine:sdl";
}

std::string sdl_stick_binding(const std::string& guid, int axis_x, int axis_y) {
    return "range:1.000000,deadzone:0.150000,threshold:0.500000,axis_y:" +
        std::to_string(axis_y) + ",axis_x:" + std::to_string(axis_x) +
        ",pad:0,port:0,guid:" + guid + ",engine:sdl";
}

void write_yuzu_sdl_binding_map(
    const std::function<void(std::string_view, std::string_view)>& set,
    const std::string& guid) {
    // Yuzu/SDL enumerates ArchStreamer uinput face buttons as
    // 0=SOUTH(A), 1=EAST(B), 2=WEST(X), 3=NORTH(Y). RetroArch udev uses
    // linux keycode order instead (2=NORTH, 3=WEST) — keep these distinct.
    set("button_a", sdl_button_binding(guid, 0));
    set("button_b", sdl_button_binding(guid, 1));
    set("button_x", sdl_button_binding(guid, 2));
    set("button_y", sdl_button_binding(guid, 3));
    set("button_l", sdl_button_binding(guid, 4));
    set("button_r", sdl_button_binding(guid, 5));
    set("button_minus", sdl_button_binding(guid, 6));
    set("button_plus", sdl_button_binding(guid, 7));
    set("button_home", sdl_button_binding(guid, 8));
    set("button_lstick", sdl_button_binding(guid, 9));
    set("button_rstick", sdl_button_binding(guid, 10));
    set("button_dup", sdl_button_binding(guid, 11));
    set("button_ddown", sdl_button_binding(guid, 12));
    set("button_dleft", sdl_button_binding(guid, 13));
    set("button_dright", sdl_button_binding(guid, 14));
    set("button_sl", sdl_button_binding(guid, 4));
    set("button_sr", sdl_button_binding(guid, 5));
    set("button_zl", sdl_axis_trigger_binding(guid, 2));
    set("button_zr", sdl_axis_trigger_binding(guid, 5));
    set("button_screenshot", "[empty]");
    set("lstick", sdl_stick_binding(guid, 0, 1));
    set("rstick", sdl_stick_binding(guid, 3, 4));
    set("motionleft", "[empty]");
    set("motionright", "[empty]");
    set("type", "0");
}

void write_yuzu_player_sdl_controls(
    std::string& contents,
    int player_index,
    const std::string& guid) {
    const std::string prefix = "player_" + std::to_string(player_index) + "_";
    const auto set = [&](std::string_view suffix, std::string_view value) {
        set_qt_ini_group_value(contents, "Controls", std::string(prefix) + std::string(suffix), value);
        set_qt_ini_group_value(
            contents,
            "Controls",
            std::string(prefix) + std::string(suffix) + "\\default",
            "false");
    };

    write_yuzu_sdl_binding_map(set, guid);
    set("connected", "true");
}

void write_yuzu_input_profile(const std::filesystem::path& path, const std::string& guid) {
    std::string contents = "[Controls]\n";
    const auto set = [&](std::string_view key, std::string_view value) {
        set_qt_ini_value(contents, key, value);
        set_qt_ini_value(contents, std::string(key) + "\\default", "false");
    };
    write_yuzu_sdl_binding_map(set, guid);
    // type\\default stays true in personal PS4.ini; keep bindings marked custom.
    set_qt_ini_value(contents, "type\\default", "true");

    std::filesystem::create_directories(path.parent_path());
    std::ofstream out(path, std::ios::trunc);
    if (!out) {
        throw std::runtime_error("failed to write Yuzu input profile: " + path.string());
    }
    out << contents;
}

void ensure_yuzu_qt_config(
    const YuzuUserProfile& profile,
    bool force_opengl,
    bool force_vulkan,
    int vulkan_device,
    int resolution_scale) {
    const auto config_dir = profile.xdg_config_home / "yuzu";
    const auto config_path = config_dir / "qt-config.ini";
    std::filesystem::create_directories(config_dir);

    const auto yuzu_data = profile.xdg_data_home / "yuzu";
    const auto nand = (yuzu_data / "nand").string();
    const auto sdmc = (yuzu_data / "sdmc").string();
    const auto load = (yuzu_data / "load").string();
    const auto dump = (yuzu_data / "dump").string();
    const auto tas = (yuzu_data / "tas").string();
    std::filesystem::create_directories(yuzu_data / "tas");
    std::filesystem::create_directories(yuzu_data / "screenshots");
    std::filesystem::create_directories(yuzu_data / "nand" / "system" / "Contents" / "registered");
    std::filesystem::create_directories(yuzu_data / "nand" / "user" / "Contents" / "registered");
    std::filesystem::create_directories(yuzu_data / "sdmc" / "Nintendo" / "Contents" / "registered");

    std::string contents;
    if (std::filesystem::exists(config_path)) {
        std::ifstream in(config_path);
        contents.assign(std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>());
    } else {
        // Minimal first-run config: skip telemetry/privacy wizard and pin save paths.
        // Keys must live under the Qt groups Yuzu reads (UI / WebService / Data Storage).
        contents =
            "[Data%20Storage]\n"
            "use_virtual_sd=true\n"
            "use_virtual_sd\\default=true\n"
            "nand_directory=" + nand + "\n"
            "nand_directory\\default=false\n"
            "sdmc_directory=" + sdmc + "\n"
            "sdmc_directory\\default=false\n"
            "load_directory=" + load + "\n"
            "load_directory\\default=false\n"
            "dump_directory=" + dump + "\n"
            "dump_directory\\default=false\n"
            "tas_directory=" + tas + "\n"
            "tas_directory\\default=false\n"
            "\n"
            "[UI]\n"
            "confirmStop=0\n"
            "confirmStop\\default=false\n"
            "firstStart=false\n"
            "firstStart\\default=false\n"
            "calloutFlags=1\n"
            "calloutFlags\\default=false\n"
            "\n"
            "[Renderer]\n"
            "backend=0\n"
            "backend\\default=false\n"
            "\n"
            "[WebService]\n"
            "enable_telemetry=false\n"
            "enable_telemetry\\default=false\n"
            "web_api_url=https://api.yuzu-emu.org\n"
            "web_api_url\\default=true\n"
            "yuzu_token=\n"
            "yuzu_token\\default=true\n"
            "yuzu_username=\n"
            "yuzu_username\\default=true\n";
    }

    // Always force these so a half-created profile from a failed first launch recovers.
    set_qt_ini_value(contents, "nand_directory", nand);
    set_qt_ini_value(contents, "nand_directory\\default", "false");
    set_qt_ini_value(contents, "sdmc_directory", sdmc);
    set_qt_ini_value(contents, "sdmc_directory\\default", "false");
    set_qt_ini_value(contents, "load_directory", load);
    set_qt_ini_value(contents, "load_directory\\default", "false");
    set_qt_ini_value(contents, "dump_directory", dump);
    set_qt_ini_value(contents, "dump_directory\\default", "false");
    set_qt_ini_value(contents, "tas_directory", tas);
    set_qt_ini_value(contents, "tas_directory\\default", "false");
    set_qt_ini_value(contents, "firstStart", "false");
    set_qt_ini_value(contents, "firstStart\\default", "false");
    // Telemetry callout bit (0x1): pretends the consent dialog was already answered.
    set_qt_ini_value(contents, "calloutFlags", "1");
    set_qt_ini_value(contents, "calloutFlags\\default", "false");
    set_qt_ini_value(contents, "enable_telemetry", "false");
    set_qt_ini_value(contents, "enable_telemetry\\default", "false");
    set_qt_ini_value(contents, "confirmStop", "0");
    if (force_opengl) {
        // 0 = OpenGL, 1 = Vulkan. Virtual capture displays often cannot present Vulkan.
        set_qt_ini_group_value(contents, "Renderer", "backend", "0");
        set_qt_ini_group_value(contents, "Renderer", "backend\\default", "false");
        set_qt_ini_group_value(contents, "Renderer", "shader_backend", "0");
        set_qt_ini_group_value(contents, "Renderer", "shader_backend\\default", "false");
        set_qt_ini_group_value(contents, "Renderer", "perform_vulkan_check", "false");
        set_qt_ini_group_value(contents, "Renderer", "perform_vulkan_check\\default", "false");
        // Exclusive fullscreen is unreliable on Xvfb (tiny/centered black window).
        // Host launches with -geometry WxH+0+0 to fill the capture surface instead.
        set_qt_ini_group_value(contents, "UI", "fullscreen", "false");
        set_qt_ini_group_value(contents, "UI", "fullscreen\\default", "false");
    } else if (force_vulkan) {
        // Gamescope presents Vulkan cleanly; a leftover OpenGL backend from VirtualGL
        // sessions can leave the PipeWire stream blank.
        set_qt_ini_group_value(contents, "Renderer", "backend", "1");
        set_qt_ini_group_value(contents, "Renderer", "backend\\default", "false");
        set_qt_ini_group_value(contents, "Renderer", "perform_vulkan_check", "false");
        set_qt_ini_group_value(contents, "Renderer", "perform_vulkan_check\\default", "false");
    }
    if (vulkan_device >= 0) {
        // Yuzu sorts devices (discrete NVIDIA first, name descending) — not vulkaninfo order.
        set_qt_ini_group_value(
            contents, "Renderer", "vulkan_device", std::to_string(vulkan_device));
        set_qt_ini_group_value(contents, "Renderer", "vulkan_device\\default", "false");
    }
    if (resolution_scale > 0) {
        // ResolutionSetup: Res1X=2, Res2X=3, … Res6X=7
        const int scale = std::clamp(resolution_scale, 1, 6);
        const int setup = scale + 1;
        set_qt_ini_group_value(
            contents, "Renderer", "resolution_setup", std::to_string(setup));
        set_qt_ini_group_value(contents, "Renderer", "resolution_setup\\default", "false");
    }

    std::ofstream out(config_path, std::ios::trunc);
    if (!out) {
        throw std::runtime_error("failed to write Yuzu qt-config.ini: " + config_path.string());
    }
    out << contents;
}


std::optional<std::filesystem::path> find_source_appimage() {
    if (const auto env = path_from_env("ARCHSTREAMER_YUZU"); env.has_value()) {
        if (std::filesystem::is_regular_file(*env)) {
            return env;
        }
    }
    if (const auto env = path_from_env("YUZU_APPIMAGE"); env.has_value()) {
        if (std::filesystem::is_regular_file(*env)) {
            return env;
        }
    }
    if (const auto env = path_from_env("YUZU_BIN"); env.has_value()) {
        if (std::filesystem::is_regular_file(*env)) {
            return env;
        }
    }

    const auto home = home_dir();
#ifdef _WIN32
    const auto local = archstreamer_cache_directory();
    const std::vector<std::filesystem::path> candidates{
        std::filesystem::path{local} / "yuzu" / "yuzu.exe",
        home / "Downloads" / "Yuzu_WIN" / "yuzu-windows-msvc" / "yuzu.exe",
        home / "Downloads" / "yuzu-windows-msvc" / "yuzu.exe",
        home / "AppData" / "Local" / "yuzu" / "yuzu.exe",
    };
    for (const auto& candidate : candidates) {
        if (std::filesystem::is_regular_file(candidate)) {
            return candidate;
        }
        // Directory containing yuzu.exe
        if (std::filesystem::is_directory(candidate.parent_path())) {
            const auto exe = candidate.parent_path() / "yuzu.exe";
            if (std::filesystem::is_regular_file(exe)) {
                return exe;
            }
        }
    }
    // If ARCHSTREAMER_YUZU points at a directory of the MSVC build:
    if (const auto env = path_from_env("ARCHSTREAMER_YUZU"); env.has_value()) {
        if (std::filesystem::is_directory(*env)) {
            for (const char* name : {"yuzu.exe", "yuzu-cmd.exe"}) {
                const auto exe = *env / name;
                if (std::filesystem::is_regular_file(exe)) {
                    return exe;
                }
            }
        }
    }
#else
    const std::vector<std::filesystem::path> candidates{
        "/srv/emus/Switch/yuzu.AppImage",
        "/srv/emus/Switch/yuzu-20231111-030c140c0.AppImage",
        home / "Applications/yuzu.AppImage",
        home / ".local/bin/yuzu",
        "/usr/local/bin/yuzu",
        "/usr/bin/yuzu",
    };

    for (const auto& candidate : candidates) {
        if (!std::filesystem::exists(candidate)) {
            continue;
        }
        if (std::filesystem::is_regular_file(candidate)) {
            const auto name = candidate.filename().string();
            if (candidate.extension() == ".AppImage" || name == "yuzu" || name.find("yuzu") != std::string::npos) {
                return candidate;
            }
            return candidate;
        }
        if (std::filesystem::is_directory(candidate)) {
            for (const auto& entry : std::filesystem::directory_iterator(candidate)) {
                if (!entry.is_regular_file()) {
                    continue;
                }
                const auto path = entry.path();
                if (path.extension() == ".AppImage" || path.filename() == "yuzu") {
                    return path;
                }
            }
        }
    }
#endif
    return std::nullopt;
}

std::optional<std::filesystem::path> find_source_keys_dir() {
    if (const auto env = path_from_env("ARCHSTREAMER_YUZU_KEYS"); env.has_value()) {
        if (std::filesystem::is_directory(*env)) {
            return env;
        }
    }
    const auto home = home_dir();
    const std::vector<std::filesystem::path> candidates{
#ifdef _WIN32
        home / "AppData" / "Roaming" / "yuzu" / "keys",
        std::filesystem::path{archstreamer_cache_directory()} / "yuzu" / "keys",
#else
        home / ".local/share/yuzu/keys",
        home / ".config/yuzu/keys",
        "/srv/retroarch/system/yuzu/keys",
        "/srv/retroarch/system/keys",
#endif
    };
    for (const auto& candidate : candidates) {
        if (std::filesystem::is_regular_file(candidate / "prod.keys")) {
            return candidate;
        }
    }
    return std::nullopt;
}

std::optional<std::filesystem::path> find_source_ryujinx() {
    if (const auto env = path_from_env("ARCHSTREAMER_RYUJINX"); env.has_value()) {
        if (std::filesystem::is_regular_file(*env)) {
            return env;
        }
        if (std::filesystem::is_directory(*env)) {
#ifdef _WIN32
            for (const char* name : {"Ryujinx.exe", "ryujinx.exe"}) {
#else
            for (const char* name : {"Ryujinx", "ryujinx", "Ryujinx.AppImage", "ryujinx.AppImage"}) {
#endif
                const auto exe = *env / name;
                if (std::filesystem::is_regular_file(exe)) {
                    return exe;
                }
            }
        }
    }

    const auto home = home_dir();
#ifdef _WIN32
    const auto local = archstreamer_cache_directory();
    const std::vector<std::filesystem::path> candidates{
        std::filesystem::path{local} / "ryujinx" / "Ryujinx.exe",
        home / "Downloads" / "Ryujinx" / "Ryujinx.exe",
        home / "AppData" / "Local" / "Ryujinx" / "Ryujinx.exe",
    };
#else
    const std::vector<std::filesystem::path> candidates{
        "/srv/emus/Switch/Ryujinx",
        "/srv/emus/Switch/ryujinx",
        "/srv/emus/Switch/Ryujinx.AppImage",
        home / "Applications/Ryujinx.AppImage",
        home / "Applications/Ryujinx",
        home / ".local/bin/Ryujinx",
        home / ".local/bin/ryujinx",
        "/usr/local/bin/Ryujinx",
        "/usr/local/bin/ryujinx",
        "/usr/bin/Ryujinx",
        "/usr/bin/ryujinx",
    };
#endif
    for (const auto& candidate : candidates) {
        if (std::filesystem::is_regular_file(candidate)) {
            return candidate;
        }
    }
    return std::nullopt;
}

} // namespace

std::filesystem::path default_archstreamer_data_root() {
    if (const auto home = home_dir(); !home.empty()) {
#ifdef _WIN32
        const auto cache = archstreamer_cache_directory();
        if (!cache.empty()) {
            return std::filesystem::path{cache};
        }
        return home / "AppData" / "Local" / "archstreamer";
#else
        return home / ".local/share/archstreamer";
#endif
    }
    return std::filesystem::current_path() / "archstreamer-data";
}

std::filesystem::path switch_system_defaults_root() {
    return default_archstreamer_data_root() / "system" / "switch";
}

std::filesystem::path default_yuzu_runtime_root() {
    if (const auto home = home_dir(); !home.empty()) {
#ifdef _WIN32
        // %LOCALAPPDATA%\archstreamer\yuzu
        const auto cache = archstreamer_cache_directory();
        if (!cache.empty()) {
            return std::filesystem::path{cache} / "yuzu";
        }
        return home / "AppData" / "Local" / "archstreamer" / "yuzu";
#else
        return home / ".local/share/archstreamer/yuzu";
#endif
    }
    return std::filesystem::current_path() / "archstreamer-yuzu";
}

bool yuzu_runtime_available() {
#ifdef _WIN32
    const auto managed_binary = default_yuzu_runtime_root() / "yuzu.exe";
#else
    const auto managed_binary = default_yuzu_runtime_root() / "yuzu.AppImage";
#endif
    if (std::filesystem::is_regular_file(managed_binary)) {
        return true;
    }
    return find_source_appimage().has_value();
}

std::string yuzu_unavailable_message() {
    const auto root = default_yuzu_runtime_root();
#ifdef _WIN32
    return "Yuzu runtime not found. Switch titles require yuzu.exe under " + root.string() +
           " (or set ARCHSTREAMER_YUZU to a yuzu-windows-msvc build). "
           "Nintendo Switch games will not be listed until Yuzu is installed.";
#else
    return "Yuzu runtime not found. Switch titles require yuzu.AppImage under " + root.string() +
           " (or set ARCHSTREAMER_YUZU). "
           "Nintendo Switch games will not be listed until Yuzu is installed.";
#endif
}

std::optional<ResolvedStandaloneEmulator> ensure_yuzu_runtime() {
    const auto root = default_yuzu_runtime_root();
#ifdef _WIN32
    const auto managed_binary = root / "yuzu.exe";
#else
    const auto managed_binary = root / "yuzu.AppImage";
#endif
    const auto managed_keys = root / "keys";
    std::filesystem::create_directories(root);
    std::filesystem::create_directories(managed_keys);

    if (!std::filesystem::exists(managed_binary)) {
        const auto source = find_source_appimage();
        if (!source.has_value()) {
            return std::nullopt;
        }
#ifdef _WIN32
        const auto source_dir = source->parent_path();
        std::cout << "Installing Yuzu Windows build into " << root << " (from " << source_dir << ")\n";
        for (const auto& entry : std::filesystem::directory_iterator(source_dir)) {
            const auto name = entry.path().filename();
            if (name == "plugins" || name == "mediaservice") {
                std::filesystem::copy(
                    entry.path(),
                    root / name,
                    std::filesystem::copy_options::recursive |
                        std::filesystem::copy_options::overwrite_existing);
                continue;
            }
            if (!entry.is_regular_file()) {
                continue;
            }
            std::filesystem::copy_file(
                entry.path(),
                root / name,
                std::filesystem::copy_options::overwrite_existing);
        }
#else
        std::cout << "Installing Yuzu AppImage into " << managed_binary << " (from " << *source << ")\n";
        std::filesystem::copy_file(*source, managed_binary, std::filesystem::copy_options::overwrite_existing);
        std::filesystem::permissions(
            managed_binary,
            std::filesystem::perms::owner_all | std::filesystem::perms::group_read |
                std::filesystem::perms::group_exec | std::filesystem::perms::others_read |
                std::filesystem::perms::others_exec,
            std::filesystem::perm_options::replace);
#endif
    }

    if (!std::filesystem::exists(managed_keys / "prod.keys")) {
        if (const auto source_keys = find_source_keys_dir(); source_keys.has_value()) {
            std::cout << "Installing Yuzu keys into " << managed_keys << " (from " << *source_keys << ")\n";
            copy_key_files(*source_keys, managed_keys);
        } else {
            std::cerr
                << "Warning: Yuzu prod.keys not found. Place keys in " << managed_keys
                << " or set ARCHSTREAMER_YUZU_KEYS.\n";
        }
    } else {
        if (const auto source_keys = find_source_keys_dir(); source_keys.has_value()) {
            copy_key_files(*source_keys, managed_keys);
        }
    }

    if (!std::filesystem::is_regular_file(managed_binary)) {
        return std::nullopt;
    }

    return ResolvedStandaloneEmulator{
        managed_binary,
        {"-f", "-g"},
        "Yuzu",
    };
}

YuzuUserProfile prepare_yuzu_user_profile(
    const SaveProfile& save_profile,
    bool force_opengl,
    bool force_vulkan,
    int vulkan_device,
    int resolution_scale) {
    YuzuUserProfile profile;
    // Isolate Qt/Yuzu paths per ArchStreamer save user.
    profile.xdg_data_home = save_profile.user_directory / "yuzu" / "xdg-data";
    profile.xdg_config_home = save_profile.user_directory / "yuzu" / "xdg-config";
    profile.keys_directory = profile.xdg_data_home / "yuzu" / "keys";

    std::filesystem::create_directories(profile.xdg_data_home / "yuzu");
    std::filesystem::create_directories(profile.xdg_config_home / "yuzu");
    std::filesystem::create_directories(profile.keys_directory);
    // Common save-related trees Yuzu may create; ensure parents exist.
    std::filesystem::create_directories(profile.xdg_data_home / "yuzu" / "nand");
    std::filesystem::create_directories(profile.xdg_data_home / "yuzu" / "sdmc");
    std::filesystem::create_directories(profile.xdg_data_home / "yuzu" / "load");
    std::filesystem::create_directories(profile.xdg_data_home / "yuzu" / "screenshot");
    std::filesystem::create_directories(profile.xdg_data_home / "yuzu" / "dump");

    const auto shared_keys = switch_system_keys_directory();
    ensure_switch_system_defaults();
    copy_key_files(shared_keys, profile.keys_directory);

    // Legacy / personal bootstrap when system/switch keys are still empty.
    if (!std::filesystem::exists(profile.keys_directory / "prod.keys")) {
        copy_key_files(default_yuzu_runtime_root() / "keys", profile.keys_directory);
    }
    if (!std::filesystem::exists(profile.keys_directory / "prod.keys")) {
        if (const auto source_keys = find_source_keys_dir(); source_keys.has_value()) {
            copy_key_files(*source_keys, profile.keys_directory);
        }
    }

    ensure_yuzu_qt_config(profile, force_opengl, force_vulkan, vulkan_device, resolution_scale);
    return profile;
}

void configure_yuzu_archstreamer_controls(
    const YuzuUserProfile& profile,
    const std::vector<std::string>& sdl_guids) {
    if (sdl_guids.empty()) {
        std::cerr << "Warning: no ArchStreamer SDL GUIDs; Yuzu Controls left unchanged.\n";
        return;
    }

    const auto config_dir = profile.xdg_config_home / "yuzu";
    const auto config_path = config_dir / "qt-config.ini";
    const auto input_dir = config_dir / "input";
    std::filesystem::create_directories(input_dir);

    std::string contents;
    if (std::filesystem::exists(config_path)) {
        std::ifstream in(config_path);
        contents.assign(std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>());
    }
    if (contents.empty()) {
        ensure_yuzu_qt_config(profile, false, false, -1, 0);
        std::ifstream in(config_path);
        contents.assign(std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>());
    }

    set_qt_ini_group_value(contents, "Controls", "keyboard_enabled", "false");
    set_qt_ini_group_value(contents, "Controls", "keyboard_enabled\\default", "false");

    // Yuzu clears the SDL name-CRC (GUID bytes 2-3) before matching. Normalize here too
    // so callers that pass raw SDL_JoystickGetGUIDString values still work.
    const auto filter_guid = [](std::string guid) {
        if (guid.size() >= 8) {
            guid.replace(4, 4, "0000");
        }
        return guid;
    };

    for (std::size_t i = 0; i < sdl_guids.size() && i < 8; ++i) {
        if (sdl_guids[i].empty()) {
            continue;
        }
        const auto guid = filter_guid(sdl_guids[i]);
        // Same layout as ~/.config/yuzu/input/PS4.ini — selectable profiles plus active bindings.
        const auto profile_name =
            i == 0 ? std::string("ArchStreamer") : ("ArchStreamer_P" + std::to_string(i + 1));
        write_yuzu_input_profile(input_dir / (profile_name + ".ini"), guid);
        write_yuzu_player_sdl_controls(contents, static_cast<int>(i), guid);
    }

    std::ofstream out(config_path, std::ios::trunc);
    if (!out) {
        throw std::runtime_error("failed to write Yuzu Controls: " + config_path.string());
    }
    out << contents;
    std::cout
        << "Yuzu Controls: bound " << sdl_guids.size()
        << " ArchStreamer pad(s) via SDL GUID (+ input/ profile)\n";
}

std::vector<std::pair<std::string, std::string>> yuzu_launch_environment(
    const YuzuUserProfile& profile) {
    return {
        {"XDG_DATA_HOME", profile.xdg_data_home.string()},
        {"XDG_CONFIG_HOME", profile.xdg_config_home.string()},
        // gamescope headless often leaves the child without "focus"; without this SDL may
        // stop delivering joystick updates and Yuzu sees intermittent pad input.
        {"SDL_JOYSTICK_ALLOW_BACKGROUND_EVENTS", "1"},
    };
}

std::filesystem::path default_ryujinx_runtime_root() {
    if (const auto home = home_dir(); !home.empty()) {
#ifdef _WIN32
        const auto cache = archstreamer_cache_directory();
        if (!cache.empty()) {
            return std::filesystem::path{cache} / "ryujinx";
        }
        return home / "AppData" / "Local" / "archstreamer" / "ryujinx";
#else
        return home / ".local/share/archstreamer/ryujinx";
#endif
    }
    return std::filesystem::current_path() / "archstreamer-ryujinx";
}

bool ryujinx_runtime_available() {
#ifdef _WIN32
    const auto managed_binary = default_ryujinx_runtime_root() / "Ryujinx.exe";
#else
    const auto managed_binary = default_ryujinx_runtime_root() / "Ryujinx";
    const auto managed_appimage = default_ryujinx_runtime_root() / "Ryujinx.AppImage";
    if (std::filesystem::is_regular_file(managed_appimage)) {
        return true;
    }
#endif
    if (std::filesystem::is_regular_file(managed_binary)) {
        return true;
    }
    return find_source_ryujinx().has_value();
}

std::string ryujinx_unavailable_message() {
    const auto root = default_ryujinx_runtime_root();
#ifdef _WIN32
    return "Ryujinx runtime not found. Place Ryujinx.exe under " + root.string() +
           " (or set ARCHSTREAMER_RYUJINX). Link backends that need Ryujinx will stay unavailable.";
#else
    return "Ryujinx runtime not found. Place Ryujinx under " + root.string() +
           " (or set ARCHSTREAMER_RYUJINX). Link backends that need Ryujinx will stay unavailable.";
#endif
}

std::optional<ResolvedStandaloneEmulator> ensure_ryujinx_runtime() {
    const auto root = default_ryujinx_runtime_root();
    const auto keys_dir = root / "keys";
#ifdef _WIN32
    const auto managed_binary = root / "Ryujinx.exe";
#else
    auto managed_binary = root / "Ryujinx";
    const auto managed_appimage = root / "Ryujinx.AppImage";
#endif
    std::filesystem::create_directories(root);
    std::filesystem::create_directories(keys_dir);

#ifdef _WIN32
    if (!std::filesystem::exists(managed_binary)) {
#else
    if (!std::filesystem::exists(managed_binary) && !std::filesystem::exists(managed_appimage)) {
#endif
        const auto source = find_source_ryujinx();
        if (!source.has_value()) {
            return std::nullopt;
        }
#ifdef _WIN32
        const auto source_dir = source->parent_path();
        std::cout << "Installing Ryujinx Windows build into " << root << " (from " << source_dir << ")\n";
        for (const auto& entry : std::filesystem::directory_iterator(source_dir)) {
            if (!entry.is_regular_file() && !entry.is_directory()) {
                continue;
            }
            const auto name = entry.path().filename();
            if (entry.is_directory()) {
                std::filesystem::copy(
                    entry.path(),
                    root / name,
                    std::filesystem::copy_options::recursive |
                        std::filesystem::copy_options::skip_existing);
            } else {
                std::filesystem::copy_file(
                    entry.path(),
                    root / name,
                    std::filesystem::copy_options::skip_existing);
            }
        }
#else
        const auto destination =
            (source->extension() == ".AppImage") ? managed_appimage : managed_binary;
        std::cout << "Installing Ryujinx into " << destination << " (from " << *source << ")\n";
        std::filesystem::copy_file(*source, destination, std::filesystem::copy_options::overwrite_existing);
        std::filesystem::permissions(
            destination,
            std::filesystem::perms::owner_all | std::filesystem::perms::group_read |
                std::filesystem::perms::group_exec | std::filesystem::perms::others_read |
                std::filesystem::perms::others_exec,
            std::filesystem::perm_options::replace);
        managed_binary = destination;
#endif
    }

    // Prefer Yuzu managed keys, then personal installs.
    copy_key_files(default_yuzu_runtime_root() / "keys", keys_dir);
    if (!std::filesystem::is_regular_file(keys_dir / "prod.keys")) {
        if (const auto source_keys = find_source_keys_dir(); source_keys.has_value()) {
            copy_key_files(*source_keys, keys_dir);
        }
    }

#ifdef _WIN32
    if (!std::filesystem::is_regular_file(managed_binary)) {
        return std::nullopt;
    }
    return ResolvedStandaloneEmulator{managed_binary, {"--fullscreen"}, "Ryujinx"};
#else
    if (std::filesystem::is_regular_file(managed_appimage)) {
        return ResolvedStandaloneEmulator{managed_appimage, {"--fullscreen"}, "Ryujinx"};
    }
    if (std::filesystem::is_regular_file(managed_binary)) {
        return ResolvedStandaloneEmulator{managed_binary, {"--fullscreen"}, "Ryujinx"};
    }
    if (const auto source = find_source_ryujinx(); source.has_value()) {
        return ResolvedStandaloneEmulator{*source, {"--fullscreen"}, "Ryujinx"};
    }
    return std::nullopt;
#endif
}

std::optional<ResolvedStandaloneEmulator> resolve_switch_runtime() {
    if (ryujinx_runtime_available()) {
        return ensure_ryujinx_runtime();
    }
    if (yuzu_runtime_available()) {
        return ensure_yuzu_runtime();
    }
    return std::nullopt;
}

std::string switch_runtime_unavailable_message() {
    return "No Switch emulator found. Install Ryujinx (preferred) under " +
        default_ryujinx_runtime_root().string() +
        " or Yuzu under " + default_yuzu_runtime_root().string() +
        " (or set ARCHSTREAMER_RYUJINX / ARCHSTREAMER_YUZU).";
}

namespace {

void ensure_ryujinx_config(
    const std::filesystem::path& config_path,
    bool enable_ldn_mitm,
    int resolution_scale) {
    std::filesystem::create_directories(config_path.parent_path());
    nlohmann::json cfg = nlohmann::json::object();
    if (std::filesystem::is_regular_file(config_path)) {
        try {
            std::ifstream in(config_path);
            cfg = nlohmann::json::parse(in, nullptr, /*allow_exceptions=*/true);
            if (!cfg.is_object()) {
                cfg = nlohmann::json::object();
            }
        } catch (const nlohmann::json::exception&) {
            cfg = nlohmann::json::object();
        }
    }

    // 0=Disabled, 1=LdnRyu, 2=LdnMitm (same-network / same-host Link).
    cfg["multiplayer_mode"] = enable_ldn_mitm ? 2 : 1;
    cfg["enable_internet_access"] = false;
    cfg["enable_vsync"] = true;
    cfg["dram_size"] = 3; // 12 GiB guest DRAM (0 is too small for Sword/Shield)

    // Headless gamescope cannot dismiss Avalonia dialogs — disable anything that
    // blocks before LoadGuestApplication.
    cfg["check_updates_on_start"] = false;
    cfg["update_checker_type"] = "Disabled";
    cfg["show_confirm_exit"] = false;
    cfg["skip_user_profiles"] = true;
    cfg["enable_discord_integration"] = false;
    cfg["disable_input_when_out_of_focus"] = false;

    if (resolution_scale > 0) {
        cfg["res_scale"] = std::clamp(resolution_scale, 1, 4);
    }

    std::ofstream out(config_path, std::ios::trunc);
    if (!out) {
        throw std::runtime_error("failed to write Ryujinx Config.json: " + config_path.string());
    }
    out << cfg.dump(2) << '\n';
}

} // namespace

RyujinxUserProfile prepare_ryujinx_user_profile(
    const SaveProfile& save_profile,
    bool enable_ldn_mitm,
    int resolution_scale) {
    RyujinxUserProfile profile;
    profile.xdg_config_home = save_profile.user_directory / "ryujinx" / "xdg-config";
    profile.data_root = profile.xdg_config_home / "Ryujinx";
    profile.keys_directory = profile.data_root / "system";

    std::filesystem::create_directories(profile.data_root / "bis" / "user" / "save");
    std::filesystem::create_directories(profile.keys_directory);
    std::filesystem::create_directories(save_profile.user_directory / "switch" / "saves");

    ensure_switch_system_defaults();
    copy_key_files(switch_system_keys_directory(), profile.keys_directory);
    if (!std::filesystem::is_regular_file(profile.keys_directory / "prod.keys")) {
        copy_key_files(default_ryujinx_runtime_root() / "keys", profile.keys_directory);
    }
    if (!std::filesystem::is_regular_file(profile.keys_directory / "prod.keys")) {
        copy_key_files(default_yuzu_runtime_root() / "keys", profile.keys_directory);
    }
    if (!std::filesystem::is_regular_file(profile.keys_directory / "prod.keys")) {
        if (const auto source_keys = find_source_keys_dir(); source_keys.has_value()) {
            copy_key_files(*source_keys, profile.keys_directory);
        }
    }

    ensure_ryujinx_firmware(profile.data_root);

    ensure_ryujinx_config(
        profile.data_root / "Config.json",
        enable_ldn_mitm,
        resolution_scale);
    return profile;
}

namespace {

// SDL GUID (32 hex) → Ryujinx GamepadSDL2 id: "{index}-{Guid-style}".
std::string ryujinx_device_id_from_sdl_guid(std::size_t index, const std::string& sdl_guid) {
    if (sdl_guid.size() < 32) {
        return std::to_string(index) + "-" + sdl_guid;
    }
    auto byte = [&](std::size_t i) { return sdl_guid.substr(i * 2, 2); };
    const std::string a = byte(3) + byte(2) + byte(1) + byte(0);
    const std::string b = byte(5) + byte(4);
    const std::string c = byte(7) + byte(6);
    const std::string d = byte(8) + byte(9);
    const std::string e = byte(10) + byte(11) + byte(12) + byte(13) + byte(14) + byte(15);
    return std::to_string(index) + "-" + a + "-" + b + "-" + c + "-" + d + "-" + e;
}

nlohmann::json ryujinx_pro_controller_sdl_binding(
    std::size_t player_index,
    const std::string& sdl_guid,
    const std::string& pad_name) {
    nlohmann::json entry = {
        {"left_joycon_stick",
         {{"joystick", "Left"},
          {"invert_stick_x", false},
          {"invert_stick_y", false},
          {"rotate90_cw", false},
          {"stick_button", "LeftStick"}}},
        {"right_joycon_stick",
         {{"joystick", "Right"},
          {"invert_stick_x", false},
          {"invert_stick_y", false},
          {"rotate90_cw", false},
          {"stick_button", "RightStick"}}},
        {"deadzone_left", 0.1},
        {"deadzone_right", 0.1},
        {"range_left", 1.0},
        {"range_right", 1.0},
        {"trigger_threshold", 0.5},
        {"motion",
         {{"motion_backend", "GamepadDriver"},
          {"sensitivity", 100},
          {"gyro_deadzone", 1},
          {"enable_motion", false}}},
        {"rumble", {{"strong_rumble", 1.0}, {"weak_rumble", 1.0}, {"enable_rumble", false}}},
        {"led",
         {{"enable_led", false},
          {"turn_off_led", false},
          {"use_rainbow", false},
          {"led_color", 0}}},
        {"left_joycon",
         {{"button_minus", "Back"},
          {"button_l", "LeftShoulder"},
          {"button_zl", "LeftTrigger"},
          {"button_sl", "Unbound"},
          {"button_sr", "Unbound"},
          {"dpad_up", "DpadUp"},
          {"dpad_down", "DpadDown"},
          {"dpad_left", "DpadLeft"},
          {"dpad_right", "DpadRight"}}},
        {"right_joycon",
         {{"button_plus", "Start"},
          {"button_r", "RightShoulder"},
          {"button_zr", "RightTrigger"},
          {"button_sl", "Unbound"},
          {"button_sr", "Unbound"},
          {"button_x", "Y"},
          {"button_b", "A"},
          {"button_y", "X"},
          {"button_a", "B"}}},
        {"version", 1},
        {"backend", "GamepadSDL2"},
        {"id", ryujinx_device_id_from_sdl_guid(player_index, sdl_guid)},
        {"name", pad_name},
        {"controller_type", "ProController"},
        {"player_index", "Player" + std::to_string(player_index + 1)},
    };
    return entry;
}

// Matches linux_uinput button registration order (SOUTH…DPAD_RIGHT) + ABS axes.
std::string archstreamer_sdl_gamecontroller_mapping(
    const std::string& sdl_guid,
    const std::string& name) {
    return sdl_guid + "," + name +
        ",platform:Linux,a:b0,b:b1,x:b2,y:b3,back:b4,guide:b5,start:b6,"
        "leftstick:b7,rightstick:b8,leftshoulder:b9,rightshoulder:b10,"
        "dpup:b11,dpdown:b12,dpleft:b13,dpright:b14,"
        "leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a4,righttrigger:a5";
}

} // namespace

void configure_ryujinx_archstreamer_controls(
    RyujinxUserProfile& profile,
    const std::vector<std::string>& sdl_guids) {
    if (sdl_guids.empty()) {
        std::cerr << "Warning: no ArchStreamer SDL GUIDs; Ryujinx input_config left unchanged.\n";
        return;
    }

    const auto config_path = profile.data_root / "Config.json";
    nlohmann::json cfg = nlohmann::json::object();
    if (std::filesystem::is_regular_file(config_path)) {
        try {
            std::ifstream in(config_path);
            cfg = nlohmann::json::parse(in, nullptr, /*allow_exceptions=*/true);
            if (!cfg.is_object()) {
                cfg = nlohmann::json::object();
            }
        } catch (const nlohmann::json::exception&) {
            cfg = nlohmann::json::object();
        }
    }

    nlohmann::json input = nlohmann::json::array();
    std::string mappings;
    for (std::size_t i = 0; i < sdl_guids.size() && i < 8; ++i) {
        if (sdl_guids[i].empty()) {
            continue;
        }
        const auto name =
            i == 0 ? std::string("ArchStreamer") : ("ArchStreamer_P" + std::to_string(i + 1));
        input.push_back(ryujinx_pro_controller_sdl_binding(i, sdl_guids[i], name));
        if (!mappings.empty()) {
            mappings.push_back('\n');
        }
        mappings += archstreamer_sdl_gamecontroller_mapping(sdl_guids[i], name);
    }
    cfg["input_config"] = std::move(input);
    cfg["use_input_global_config"] = false;
    cfg["disable_input_when_out_of_focus"] = false;

    std::ofstream out(config_path, std::ios::trunc);
    if (!out) {
        throw std::runtime_error("failed to write Ryujinx input_config: " + config_path.string());
    }
    out << cfg.dump(2) << '\n';
    profile.sdl_gamecontroller_config = std::move(mappings);
    std::cout
        << "Ryujinx Controls: bound " << sdl_guids.size()
        << " ArchStreamer pad(s) via GamepadSDL2 (+ SDL_GAMECONTROLLERCONFIG)\n";
}

std::vector<std::pair<std::string, std::string>> ryujinx_launch_environment(
    const RyujinxUserProfile& profile) {
    std::vector<std::pair<std::string, std::string>> env{
        {"XDG_CONFIG_HOME", profile.xdg_config_home.string()},
        {"SDL_JOYSTICK_ALLOW_BACKGROUND_EVENTS", "1"},
    };
    if (!profile.sdl_gamecontroller_config.empty()) {
        env.emplace_back("SDL_GAMECONTROLLERCONFIG", profile.sdl_gamecontroller_config);
    }
    return env;
}

} // namespace archstreamer
